#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_VIDEO_ROCKCHIP) += rk_vop.o
obj-$(CONFIG_DISPLAY_MIPI) += rk_mipi.o
obj-$(CONFIG_DISPLAY_EDP) += rk_edp.o
obj-$(CONFIG_DISPLAY_LVDS) += rk_lvds.o
obj-$(CONFIG_DISPLAY_HDMI) += rk_hdmi.o
