#
# Copyright (C) 2017 Rockchip Electronics
# Author:Eric Gao <eric.gao@rock-chips.com>
#
# SPDX-License-Identifier:  GPL-2.0+
#

obj-$(CONFIG_BOARD_COMMON)  += common.o
obj-$(CONFIG_MISC_COMMON) += misc.o
